[package]
name = "oriel"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
gtk = "0.17.1"
pest = "2.7.1"
pest_derive = { version = "2.7.1", features = ["grammar-extras"] }
thiserror = "1.0.44"
getopts = "0.2"
